### ISSUE TITLE
my computer is macbookpro ,  how can I use libigl in my computer 

### ISSUE THREAD

**Issue by L-liyi** [itoru257/libigl-Demo-Mac#1]

**Comment by itoru257** [comment]
Open "libigl-Demo-Mac.xcodeproj" file in Xcode. And build it.

For more information, please see below.
https://libigl.github.io

**Comment by L-liyi** [comment]
but，I don't have "libigl-Demo-Mac.xcodeproj" file 
what I can do ？

**Comment by itoru257** [comment]
https://github.com/itoru257/libigl-Demo-Mac/tree/master/libigl-Demo-Mac.xcodeproj

**Comment by L-liyi** [comment]
> https://github.com/itoru257/libigl-Demo-Mac/tree/master/libigl-Demo-Mac.xcodeproj

it can't work 
![image](https://user-images.githubusercontent.com/58982907/87791776-6d60a300-c875-11ea-9b35-43d996679a2e.png)

**Comment by itoru257** [comment]
Please read "https://github.com/itoru257/libigl-Demo-Mac/blob/master/README.md" and install the library.

**Comment by itoru257** [comment]
Take a look at this one.
https://www.youtube.com/watch?v=fJveW3f5p0c
